packages:
  - "apps/*"
  - "packages/*"

strictPeerDependencies: true

allowBuilds:
  unrs-resolver: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
